# Generated by Django 6.0.2 on 2026-02-27 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.URLField(default='Null', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='author',
            name='remote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
